= flixctl
:toc:
:toc-placement: preamble
:toclevels: 3
:Some attr: Some value

// Need some preamble to get TOC:
{empty}

image:https://travis-ci.com/eschizoid/flixctl.svg?branch=master["Build Status", link="https://travis-ci.com/eschizoid/flixctl"]
image:https://goreportcard.com/badge/github.com/eschizoid/flixctl["Go Report Card", link="https://goreportcard.com/report/github.com/eschizoid/flixctl"]
image:https://godoc.org/github.com/eschizoid/flixctl?status.svg["GoDoc", link="https://godoc.org/github.com/eschizoid/flixctl"]

Inspired by `kubectl`, `flixctl` aims to provide a programmatic way for controlling the infrastructure necessary for a
true MaaS (Movies as a Service) architecture. All flixctl commands try to be as simple as possible so they can be
abstracted using Slack API's.

=== Architecture

=== Components

==== Hardware (AWS)
* https://aws.amazon.com/api-gateway[API Geteway]
* https://aws.amazon.com/ebs[EBS]
* https://aws.amazon.com/ec2[EC2]
* https://aws.amazon.com/glacier[Glacier]
* https://aws.amazon.com/lambda[Lambda]
* https://aws.amazon.com/sns[SNS]

==== Software
* https://letsencrypt.org/[Let's Encrypt]
* https://www.duckdns.org/[Duck DNS]
* https://github.com/lukas2511/dehydrated[Dehydrated]
* https://github.com/Jackett/Jackett[Jackett]
* https://github.com/nzbget[NZBGet]
* https://github.com/tidusjar/Ombi[Ombi]
* https://github.com/plexinc/plex-media-player[Plex]
* https://github.com/Radarr/Radarr[Radarr]
* https://github.com/Tautulli/Tautulli[Tautulli]
* https://github.com/transmission/transmission[Transmission]
* https://api.slack.com/slash-commands[Slack Slash Commands]
* https://github.com/Sonarr/Sonarr[Sonarr]
* https://github.com/adnanh/webhook[Webhooks]

=== Pre-requisites
==== Hardware
* EC2 Instance
* EBS Volume
* Glacier Vault
* S3 Bucket

==== Software
----
brew install go
brew install dep
----

==== Environment
[%header,cols=2*]
|===
|Environment Variable Name|Description

|AWS_RESOURCE_TAG_NAME_VALUE|
|BOLT_DATABASE|
|ENABLE_LIBRARY_SYNC|
|HOOKS_URL|
|FLIXCTL_HOST|
|PLEX_PASSWORD|
|PLEX_TOKEN|
|PLEX_USER|
|SLACK_LEGACY_TOKEN|
|SLACK_LIBRARY_INCOMING_HOOK_URL|
|SLACK_MOVIES_SEARCH_TOKEN|
|SLACK_PLEX_INCOMING_HOOK_URL|
|SLACK_PLEX_TOKEN|
|SLACK_SHOWS_SEARCH_TOKEN|
|SLACK_TAUTULLI_INCOMING_HOOK_URL|
|SLACK_TORRENT_INCOMING_HOOK_URL|
|SLACK_STATUS_TOKEN|
|TAUTULI_API_KEY|
|TR_AUTH|
|UPDATE_VENDOR|
|===

=== Dependencies
----
make dep
----

=== Lints
----
make lint
----

=== Build (CLI and λ's)
----
make build
----

=== Install flixctl
----
make install
----

=== Deploy λ's
----
make deploy-lambdas
----

=== Usage
==== ```flixctl```
----
$ flixctl --help
To Control The Following flixctl Components:
  * Library
  * Plex
  * Torrent

Usage:
  flixctl [command]

Available Commands:
  help        Help about any command
  library     To Control Media Library
  plex        To Control Plex Media Center
  torrent     To Control Torrent Client
  version     To Get flixctl Version

Flags:
  -h, --help   help for flixctl

Use "flixctl [command] --help" for more information about a command.
----
==== ```flixctl plex```
----
$ flixctl plex --help
To Control Plex Media Center

Usage:
  flixctl plex [command]

Available Commands:
  start       To Start Plex
  status      To Get Plex Status
  stop        To Stop Plex
  token       To Get Plex Token

Flags:
  -h, --help   help for plex

Use "flixctl plex [command] --help" for more information about a command.
----
==== ```flixctl library```
----
$ flixctl library --help
To Control Media Library

Usage:
  flixctl library [command]

Available Commands:
  catalogue   To Show Plex And Library Catalogue
  delete      To Delete Archives From Library
  download    To Download Movies Or Shows
  initiate    To Initiate Library Jobs
  inventory   To Show Library Inventory
  jobs        To List Library Jobs
  sync        To Sync Plex Watched Movies And Shows
  upload      To Upload Movies Or Shows

Flags:
  -h, --help   help for library

Use "flixctl library [command] --help" for more information about a command.
----
==== ```flixctl torrent```
----
$ flixctl torrent --help
To Control Torrent Client

Usage:
  flixctl torrent [command]

Available Commands:
  download    To Download a Torrent
  search      To Search for Torrents
  status      To Show Torrents Status

Flags:
  -h, --help   help for torrent

Use "flixctl torrent [command] --help" for more information about a command.
----

=== Examples
==== ```flixctl```
----
$ flixctl version
----
==== ```flixctl plex```
----
$ flixctl plex start \
    --slack-notification "true" \
    --slack-notification-channel "monitoring"

$ flixctl plex status \
    --slack-notification "false"

$ flixctl plex stop \
    --slack-notification "true" \
    --slack-notification-channel "monitoring"

$ flixctl plex token
----
==== ```flixctl torrent```
----
$ flixctl torrent download \
    --magnet-link "magnet:?xt=urn:btih:80707BDD08084AFD5996BF88DC879BA1B1C0CB67&dn=T2+Trainspotting+2017+BDRip+1080p&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969%2Fannounce&tr=udp%3A%2F%2Feddie4.nl%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce"

$ flixctl torrent search \
    --keywords Trainspotting \
    --minimum-quality 1080 \
    --slack-notification "true" \
    --slack-notification-channel "monitoring"

$ flixctl torrent status \
    --slack-notification "true" \
    --slack-notification-channel "monitoring"
----
==== ```flixctl library```
----
$ flixctl library catalogue \
    --filter <all|archived|live|unwatched|watched>

$ flixctl library delete \
    --archive-id U1IDD8GVNYGhtnbtjfr7_oV-h9hNqcjAkR1RfCdBrL8uoQdlViB0TtGUvnWrKkLM8nlf7LEZTV_X8CuXVoMKtnEBOBELgmmuQDIZkSA9xU-mlWJMSxf_132VcP4RTXNxZ7MdmTdNGA

$ flixctl library download \
    --job-id RP5RUuUyX0PxGlbipyeUr-pjPB74lYqOqXT6mA6sjrDU3y2Y7-ggAgQepNKeuULMpw8RIhNo6U60bTIONhxVI9dg61az \
    --target-file "/plex/movies/glacier/movie-$(date +%Y-%m-%d.%H:%M:%S).zip"

$ flixctl library inventory \
    --enable-sync "true" \
    --max-upload-items "2" \
    --job-id RP5RUuUyX0PxGlbipyeUr-pjPB74lYqOqXT6mA6sjrDU3y2Y7-ggAgQepNKeuULMpw8RIhNo6U60bTIONhxVI9dg61az \
    --slack-notification "true" \
    --slack-notification-channel "monitoring"

$ flixctl library inventory \
    --enable-sync "false" \
    --slack-notification "true" \
    --slack-notification-channel "monitoring"

$ flixctl library initiate

$ flixctl library initiate \
    --archive-id U1IDD8GVNYGhtnbtjfr7_oV-h9hNqcjAkR1RfCdBrL8uoQdlViB0TtGUvnWrKkLM8nlf7LEZTV_X8CuXVoMKtnEBOBELgmmuQDIZkSA9xU-mlWJMSxf_132VcP4RTXNxZ7MdmTdNGA \
    --slack-notification "true" \
    --slack-notification-channel "monitoring"

$ flixctl library jobs \
    --filter <all|archive-retrieval|inventory-retrieval> \
    --slack-notification "true" \
    --slack-notification-channel "monitoring"

$ flixctl library sync \
    --slack-notification "true" \
    --slack-notification-channel "monitoring"

$ /home/webhook/go/bin/flixctl library upload \
    --enable-batch-mode "true"

$ flixctl library upload \
    --enable-batch-mode "false" \
    --source-file "/plex/movies/trainspoting/Trainspoting.mkv"
----
